### ISSUE TITLE
为什么我引入就报这个错误

### ISSUE THREAD

**Issue by codesourse** [jcccn/Baidu-Map-SDK-iOS#2]
Undefined symbols for architecture armv7:
  "_MKLaunchOptionsShowsTrafficKey", referenced from:
      ___42-[B2_MapGuidanceViewController showAllMap]_block_invoke in B2_MapGuidanceViewController.o
  "_MKLaunchOptionsDirectionsModeDriving", referenced from:
      ___42-[B2_MapGuidanceViewController showAllMap]_block_invoke in B2_MapGuidanceViewController.o
  "_OBJC_CLASS_$_MKPlacemark", referenced from:
      objc-class-ref in B2_MapGuidanceViewController.o
  "_MKLaunchOptionsDirectionsModeKey", referenced from:
      ___42-[B2_MapGuidanceViewController showAllMap]_block_invoke in B2_MapGuidanceViewController.o
  "_OBJC_CLASS_$_MKMapItem", referenced from:
      objc-class-ref in B2_MapGuidanceViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

能帮忙解决一下吗？

**Comment by jcccn** [comment]
请问引用的是哪个.a库文件？

方便的话，能否发一个demo工程过来看看？

**Comment by codesourse** [comment]
发你邮箱jccuestc@gmail.com了，请注意查收。

**Comment by codesourse** [comment]
主要还是

**Comment by codesourse** [comment]
主要还是这段代码：    [MKMapItem openMapsWithItems:[NSArray arrayWithObjects:currentLocation, toLocation, nil] launchOptions:[NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:MKLaunchOptionsDirectionsModeDriving, [NSNumber numberWithBool:YES], nil] forKeys:[NSArray arrayWithObjects:MKLaunchOptionsDirectionsModeKey, MKLaunchOptionsShowsTrafficKey, nil]]];
引起的

**Comment by jcccn** [comment]
将MapKit.framework添加进来就OK

**Comment by jcccn** [comment]
你邮件的附件放在google drive的，但是我没有查看的权限
