### ISSUE TITLE
framework not found BaiduMapAPIBaseMap

### ISSUE THREAD

**Issue by benwu7** [jcccn/Baidu-Map-SDK-iOS#3]
从2.6更新到2.7以后遇到了这个情况。怎么回事？

framework not found BaiduMapAPIBaseMap

**Comment by benwu7** [comment]
ok，我发现是因为我用了BaseMap，如果用all的话就可以了

**Comment by benwu7** [comment]
但是又出现了新的问题：
引擎初始化失败

**Comment by jcccn** [comment]
我晚上回去修复一下，应该是podspev配置文件的问题

**Comment by benwu7** [comment]
可能不是你的问题，我的dev build是可以working的。release build不行。。。反正百度地图有各种bug。。。

**Comment by jcccn** [comment]
已经修复了。重新安装测试下吧
